server.port=8761
spring.application.name=discovery-service

# Standalone Eureka Server Setup
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Avoid console spam from empty registry
eureka.server.wait-time-in-ms-when-sync-empty=0
