networks:
  stormshield-net:
    driver: bridge

services:
  # ----------------------------------------
  # INFRASTRUCTURE DATABASES & BROKER
  # ----------------------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - stormshield-net

  mysql-db:
    image: mysql:8.0
    container_name: stormshield-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - stormshield-net
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------------------------------
  # DISCOVERY & REGISTRY REGION
  # ----------------------------------------
  discovery-service:
    build: ./backend/discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - stormshield-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------------------------------
  # API GATEWAY
  # ----------------------------------------
  gateway-service:
    build: ./backend/gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - stormshield-net
    depends_on:
      - discovery-service

  # ----------------------------------------
  # BUSINESS MICROSERVICES
  # ----------------------------------------
  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    networks:
      - stormshield-net
    depends_on:
      mysql-db:
        condition: service_healthy

  shelter-service:
    build: ./backend/shelter-service
    container_name: shelter-service
    ports:
      - "8082:8082"
    networks:
      - stormshield-net
    depends_on:
      mysql-db:
        condition: service_healthy

  alert-service:
    build: ./backend/alert-service
    container_name: alert-service
    ports:
      - "8083:8083"
    networks:
      - stormshield-net
    depends_on:
      mysql-db:
        condition: service_healthy

  support-service:
    build: ./backend/support-service
    container_name: support-service
    ports:
      - "8085:8085"
    networks:
      - stormshield-net
    depends_on:
      mysql-db:
        condition: service_healthy

  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    ports:
      - "8086:8086"
    networks:
      - stormshield-net
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  db-data:
