server.port=8083
spring.application.name=alert-service

# Custom Mock Configs
notification.mock.enabled=true


# Weather API Config
external.weather.api.base-url=https://api.openweathermap.org/data/2.5/weather
external.weather.api.key=${WEATHER_API_KEY:f0000000000000000000000000000000}
external.weather.api.units=metric

# Weather Rule Thresholds
weather.rules.rain.high-mm=30.0
weather.rules.rain.critical-mm=100.0
weather.rules.wind.medium-kmh=40.0
weather.rules.wind.critical-kmh=80.0

# Weather Monitoring & Scheduler
weather.monitoring.enabled=true
weather.monitoring.scan-interval-ms=900000
weather.monitoring.max-provinces-per-scan=63
weather.monitoring.active-provinces-only=false

# Weather Demo Mode
weather.demo-mode=true
weather.demo-scenario=CENTRAL_STORM

eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

spring.datasource.url=jdbc:mysql://mysql-db:3306/stormshield_alert?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
