server.port=8080
spring.application.name=gateway-service

# Eureka Discovery
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/

# ----------------------------------------
# Dynamic Routing to Microservices via Eureka
# lb:// means Gateway will find service by spring.application.name in Eureka
# ----------------------------------------

# Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# Shelter Service
spring.cloud.gateway.routes[1].id=shelter-service
spring.cloud.gateway.routes[1].uri=lb://shelter-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/shelters/**

# Alert Service
# Handles official alerts and user incident reports
spring.cloud.gateway.routes[2].id=alert-service
spring.cloud.gateway.routes[2].uri=lb://alert-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/alerts/**,/api/v1/incident-reports/**

# Support Service
spring.cloud.gateway.routes[3].id=support-service
spring.cloud.gateway.routes[3].uri=lb://support-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/support-requests/**

# Notification Service
spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://notification-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/notifications/**

# ----------------------------------------
# Global CORS Configuration
# Allows React frontend and mobile clients to call API Gateway
# ----------------------------------------
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*